// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://bosbbfquxbhvhzhvenro.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJvc2JiZnF1eGJodmh6aHZlbnJvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTgzNTQ1MjEsImV4cCI6MjA3MzkzMDUyMX0.1JnD7DUZts9FD580XorA0C37BJKuTFFtQzKEx_DjFZw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});